qrcode:
  hashKey: 6h5K8dapxfFdVKAS
  loadFromConfig: false
  companyId: VNG
  officeId: CAMPUS
  baseUrl: https://1612145.online/api/employee
  methodName: /public/genqrcode
resetpassword:
  hashKey: 6h5K8dapxfFdVKAS
  baseUrl: https://1612145.online/api/gateway
  methodName: /public/resetpassword/update
createorder:
  hashKey: 6h5K8dapxfFdVKAS
  baseUrl: https://1612145.online/api/admin
  methodName: /public/createorder
submittrans:
  hashKey: 6h5K8dapxfFdVKAS
  baseUrl: https://1612145.online/api/admin
  methodName: /public/submittrans
